on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: Deploy     
      uses: utahcon/action-scp@v1.1.3
      with:
        server: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "html/*"
        destination: "/var/www/html"
        recursive: true